### ISSUE TITLE
Getting 408

### ISSUE THREAD

**Issue by taylorturner** [crazy-max/docker-matomo#18]
Hello,

Fresh install on Ubuntu 16 host running on EC2. I'm trying this set up because the base image from Matomo dockerhub I was using didn't have support for GeoIP2.

Here are the logs

```
Attaching to matomo_cron, matomo, matomo_redis, matomo_db, traefik
matomo     | Setting timezone to Europe/Paris...
matomo     | Setting PHP-FPM configuration...
matomo     | Setting OpCache configuration...
matomo     | Setting Nginx configuration...
matomo     | Setting SSMTP configuration...
matomo     | Initializing Matomo files / folders...
matomo     | Checking Matomo plugins...
matomo     | Checking Matomo user-misc folder...
matomo     | Fixing permissions...
matomo     | >>
matomo     | >> Open your browser to install Matomo through the wizard
matomo     | >>
matomo     | 2019-04-16 04:04:07,887 INFO Included extra file "/etc/supervisord/matomo_watch_plugins.conf" during parsing
matomo     | 2019-04-16 04:04:07,887 INFO Included extra file "/etc/supervisord/nginx.conf" during parsing
matomo     | 2019-04-16 04:04:07,887 INFO Included extra file "/etc/supervisord/php.conf" during parsing
matomo     | 2019-04-16 04:04:07,887 INFO Set uid to user 0 succeeded
matomo     | 2019-04-16 04:04:07,895 INFO RPC interface 'supervisor' initialized
matomo     | 2019-04-16 04:04:07,895 CRIT Server 'unix_http_server' running without any HTTP authentication checking
matomo     | 2019-04-16 04:04:07,895 INFO supervisord started with pid 1
matomo     | 2019-04-16 04:04:08,898 INFO spawned: 'nginx' with pid 23
matomo     | 2019-04-16 04:04:08,899 INFO spawned: 'php' with pid 24
matomo     | 2019-04-16 04:04:08,900 INFO spawned: 'matomo_watch_plugins' with pid 25
matomo     | Setting up watches.
matomo     | Watches established.
matomo     | 2019/04/16 04:04:08 [notice] 23#23: using the "epoll" event method
matomo     | 2019/04/16 04:04:08 [notice] 23#23: nginx/1.14.2
matomo     | 2019/04/16 04:04:08 [notice] 23#23: built by gcc 8.3.0 (Alpine 8.3.0)
matomo     | 2019/04/16 04:04:08 [notice] 23#23: OS: Linux 4.4.0-1079-aws
matomo     | 2019/04/16 04:04:08 [notice] 23#23: getrlimit(RLIMIT_NOFILE): 1048576:1048576
matomo     | 2019/04/16 04:04:08 [notice] 23#23: start worker processes
matomo     | 2019/04/16 04:04:08 [notice] 23#23: start worker process 28
matomo     | 2019/04/16 04:04:08 [notice] 23#23: start worker process 29
matomo     | 2019/04/16 04:04:08 [notice] 23#23: start worker process 30
matomo     | 2019/04/16 04:04:08 [notice] 23#23: start worker process 31
matomo     | [16-Apr-2019 04:04:08] NOTICE: fpm is running, pid 24
matomo     | [16-Apr-2019 04:04:08] NOTICE: ready to handle connections
matomo     | 2019-04-16 04:04:09,932 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
matomo     | 2019-04-16 04:04:09,932 INFO success: php entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
matomo     | 2019-04-16 04:04:09,933 INFO success: matomo_watch_plugins entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
matomo_redis | 1:C 16 Apr 02:04:07.153 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
matomo_redis | 1:C 16 Apr 02:04:07.153 # Redis version=4.0.14, bits=64, commit=00000000, modified=0, pid=1, just started
matomo_redis | 1:C 16 Apr 02:04:07.153 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
matomo_redis | 1:M 16 Apr 02:04:07.154 * Running mode=standalone, port=6379.
matomo_redis | 1:M 16 Apr 02:04:07.154 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
matomo_redis | 1:M 16 Apr 02:04:07.154 # Server initialized
matomo_redis | 1:M 16 Apr 02:04:07.154 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
matomo_redis | 1:M 16 Apr 02:04:07.154 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
matomo_redis | 1:M 16 Apr 02:04:07.154 * Ready to accept connections
matomo_cron | Setting timezone to Europe/Paris...
matomo_cron | Setting PHP-FPM configuration...
matomo_cron | Setting OpCache configuration...
matomo_cron | Setting Nginx configuration...
matomo_cron | Setting SSMTP configuration...
matomo_cron | Initializing Matomo files / folders...
matomo_cron | Checking Matomo plugins...
matomo_cron | Checking Matomo user-misc folder...
matomo_cron | Fixing permissions...
matomo_cron | >>
matomo_cron | >> Sidecar cron container detected for Matomo
matomo_cron | >>
matomo_cron | Creating GeoIP cron task with the following period fields : 0 2 * * *
matomo_cron | Creating Matomo archive cron task with the following period fields : 0 * * * *
matomo_cron | Fixing permissions...
matomo_cron | 2019-04-16 04:04:08,321 INFO Included extra file "/etc/supervisord/cron.conf" during parsing
matomo_cron | 2019-04-16 04:04:08,321 INFO Included extra file "/etc/supervisord/matomo_watch_plugins.conf" during parsing
matomo_cron | 2019-04-16 04:04:08,321 INFO Set uid to user 0 succeeded
matomo_cron | 2019-04-16 04:04:08,329 INFO RPC interface 'supervisor' initialized
matomo_cron | 2019-04-16 04:04:08,329 CRIT Server 'unix_http_server' running without any HTTP authentication checking
matomo_cron | 2019-04-16 04:04:08,329 INFO supervisord started with pid 1
matomo_cron | 2019-04-16 04:04:09,332 INFO spawned: 'cron' with pid 27
matomo_cron | 2019-04-16 04:04:09,333 INFO spawned: 'matomo_watch_plugins' with pid 28
matomo_cron | crond: crond (busybox 1.29.3) started, log level 8
matomo_cron | Setting up watches.
matomo_cron | Watches established.
matomo_cron | 2019-04-16 04:04:10,342 INFO success: cron entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
matomo_cron | 2019-04-16 04:04:10,342 INFO success: matomo_watch_plugins entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
matomo_db  | 2019-04-16  2:04:07 139759790028096 [Note] mysqld (mysqld 10.2.23-MariaDB-1:10.2.23+maria~bionic) starting as process 1 ...
matomo_db  | 2019-04-16  2:04:07 139759790028096 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
matomo_db  | 2019-04-16  2:04:07 139759790028096 [Note] InnoDB: Uses event mutexes
matomo_db  | 2019-04-16  2:04:07 139759790028096 [Note] InnoDB: Compressed tables use zlib 1.2.11
matomo_db  | 2019-04-16  2:04:07 139759790028096 [Note] InnoDB: Using Linux native AIO
matomo_db  | 2019-04-16  2:04:07 139759790028096 [Note] InnoDB: Number of pools: 1
matomo_db  | 2019-04-16  2:04:07 139759790028096 [Note] InnoDB: Using SSE2 crc32 instructions
matomo_db  | 2019-04-16  2:04:07 139759790028096 [Note] InnoDB: Initializing buffer pool, total size = 256M, instances = 1, chunk size = 128M
matomo_db  | 2019-04-16  2:04:07 139759790028096 [Note] InnoDB: Completed initialization of buffer pool
matomo_db  | 2019-04-16  2:04:07 139759068067584 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
matomo_db  | 2019-04-16  2:04:07 139759790028096 [Note] InnoDB: Highest supported file format is Barracuda.
matomo_db  | 2019-04-16  2:04:07 139759790028096 [Note] InnoDB: 128 out of 128 rollback segments are active.
matomo_db  | 2019-04-16  2:04:07 139759790028096 [Note] InnoDB: Creating shared tablespace for temporary tables
matomo_db  | 2019-04-16  2:04:07 139759790028096 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
matomo_db  | 2019-04-16  2:04:07 139759790028096 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
matomo_db  | 2019-04-16  2:04:07 139759790028096 [Note] InnoDB: 5.7.25 started; log sequence number 1620192
matomo_db  | 2019-04-16  2:04:07 139758755895040 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
matomo_db  | 2019-04-16  2:04:07 139759790028096 [Note] Plugin 'FEEDBACK' is disabled.
matomo_db  | 2019-04-16  2:04:07 139759790028096 [Note] Server socket created on IP: '::'.
matomo_db  | 2019-04-16  2:04:07 139759790028096 [Warning] 'proxies_priv' entry '@% root@d65ab378b646' ignored in --skip-name-resolve mode.
matomo_db  | 2019-04-16  2:04:07 139758755895040 [Note] InnoDB: Buffer pool(s) load completed at 190416  2:04:07
matomo_db  | 2019-04-16  2:04:07 139759790028096 [Note] Reading of all Master_info entries succeded
matomo_db  | 2019-04-16  2:04:07 139759790028096 [Note] Added new Master_info '' to hash table
matomo_db  | 2019-04-16  2:04:07 139759790028096 [Note] mysqld: ready for connections.
matomo_db  | Version: '10.2.23-MariaDB-1:10.2.23+maria~bionic'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  mariadb.org binary distribution
traefik    | time="2019-04-16T02:04:07Z" level=info msg="Traefik version v1.7.10 built on 2019-03-29_12:20:34PM"
traefik    | time="2019-04-16T02:04:07Z" level=info msg="\nStats collection is disabled.\nHelp us improve Traefik by turning this feature on :)\nMore details on: https://docs.traefik.io/basics/#collected-data\n"
traefik    | time="2019-04-16T02:04:07Z" level=info msg="Preparing server http &{Address::80 TLS:<nil> Redirect:0xc0006333c0 Auth:<nil> WhitelistSourceRange:[] WhiteList:<nil> Compress:false ProxyProtocol:<nil> ForwardedHeaders:0xc0004b6dc0} with readTimeout=0s writeTimeout=0s idleTimeout=3m0s"
traefik    | time="2019-04-16T02:04:07Z" level=info msg="Preparing server https &{Address::443 TLS:0xc0002d4fc0 Redirect:<nil> Auth:<nil> WhitelistSourceRange:[] WhiteList:<nil> Compress:false ProxyProtocol:<nil> ForwardedHeaders:0xc0004b6ea0} with readTimeout=0s writeTimeout=0s idleTimeout=3m0s"
traefik    | time="2019-04-16T02:04:07Z" level=info msg="Starting server on :80"
traefik    | time="2019-04-16T02:04:08Z" level=info msg="Starting provider configuration.ProviderAggregator {}"
traefik    | time="2019-04-16T02:04:08Z" level=info msg="Starting server on :443"
traefik    | time="2019-04-16T02:04:08Z" level=info msg="Starting provider *docker.Provider {\"Watch\":true,\"Filename\":\"\",\"Constraints\":null,\"Trace\":false,\"TemplateVersion\":2,\"DebugLogGeneratedTemplate\":false,\"Endpoint\":\"unix:///var/run/docker.sock\",\"Domain\":\"mckinsey-matomo.brandcast.io\",\"TLS\":null,\"ExposedByDefault\":false,\"UseBindPortIP\":false,\"SwarmMode\":false,\"Network\":\"\",\"SwarmModeRefreshSeconds\":15}"
traefik    | time="2019-04-16T02:04:08Z" level=info msg="Starting provider *acme.Provider {\"Email\":\"taylor@brandcast.com\",\"ACMELogging\":true,\"CAServer\":\"https://acme-v02.api.letsencrypt.org/directory\",\"Storage\":\"acme.json\",\"EntryPoint\":\"https\",\"KeyType\":\"\",\"OnHostRule\":true,\"OnDemand\":false,\"DNSChallenge\":null,\"HTTPChallenge\":{\"EntryPoint\":\"http\"},\"TLSChallenge\":null,\"Domains\":null,\"Store\":{}}"
traefik    | time="2019-04-16T02:04:08Z" level=info msg="Testing certificate renew..."
traefik    | time="2019-04-16T02:04:08Z" level=info msg="Server configuration reloaded on :80"
traefik    | time="2019-04-16T02:04:08Z" level=info msg="Server configuration reloaded on :443"
traefik    | time="2019-04-16T02:04:08Z" level=info msg="Server configuration reloaded on :443"
traefik    | time="2019-04-16T02:04:08Z" level=info msg="Server configuration reloaded on :80"
traefik    | time="2019-04-16T02:04:08Z" level=info msg="The key type is empty. Use default key type 4096."
traefik    | time="2019-04-16T02:04:10Z" level=info msg="Server configuration reloaded on :80"
traefik    | time="2019-04-16T02:04:10Z" level=info msg="Server configuration reloaded on :443"
traefik    | time="2019-04-16T02:04:10Z" level=info msg=Register...
traefik    | time="2019-04-16T02:04:10Z" level=info msg="legolog: [INFO] acme: Registering account for taylor@brandcast.com"
traefik    | time="2019-04-16T02:04:10Z" level=info msg="legolog: [INFO] [mckinsey-matomo.brandcast.io] acme: Obtaining bundled SAN certificate"
traefik    | time="2019-04-16T02:04:10Z" level=info msg="legolog: [INFO] [mckinsey-matomo.brandcast.io] AuthURL: https://acme-v02.api.letsencrypt.org/acme/authz/Md5wN45VfU4KFUN1kyElQMGIfueze9n40LhDtOV2UPo"
traefik    | time="2019-04-16T02:04:10Z" level=info msg="legolog: [INFO] [mckinsey-matomo.brandcast.io] acme: Could not find solver for: tls-alpn-01"
traefik    | time="2019-04-16T02:04:10Z" level=info msg="legolog: [INFO] [mckinsey-matomo.brandcast.io] acme: use http-01 solver"
traefik    | time="2019-04-16T02:04:10Z" level=info msg="legolog: [INFO] [mckinsey-matomo.brandcast.io] acme: Trying to solve HTTP-01"
traefik    | time="2019-04-16T02:04:14Z" level=info msg="legolog: [INFO] [mckinsey-matomo.brandcast.io] The server validated our request"
traefik    | time="2019-04-16T02:04:14Z" level=info msg="legolog: [INFO] [mckinsey-matomo.brandcast.io] acme: Validations succeeded; requesting certificates"
traefik    | time="2019-04-16T02:04:18Z" level=info msg="legolog: [INFO] [mckinsey-matomo.brandcast.io] Server responded with a certificate."
traefik    | time="2019-04-16T02:04:18Z" level=info msg="Server configuration reloaded on :80"
traefik    | time="2019-04-16T02:04:18Z" level=info msg="Server configuration reloaded on :443"
```

Here is the docker-compose.yml
```
version: "3.2"

services:
  traefik:
    image: traefik:1.7-alpine
    container_name: traefik
    command:
      - "--logLevel=INFO"
      - "--defaultentrypoints=http,https"
      - "--entryPoints=Name:http Address::80 Redirect.EntryPoint:https"
      - "--entryPoints=Name:https Address::443 TLS"
      - "--docker"
      - "--docker.exposedbydefault=false"
      - "--docker.domain=mckinsey-matomo.brandcast.io"
      - "--acme=true"
      - "--acme.acmelogging=true"
      - "--acme.email=taylor@brandcast.com"
      - "--acme.storage=acme.json"
      - "--acme.entryPoint=https"
      - "--acme.onhostrule=true"
      - "--acme.httpchallenge=true"
      - "--acme.httpchallenge.entrypoint=http"
    ports:
      - target: 80
        published: 80
        protocol: tcp
      - target: 443
        published: 443
        protocol: tcp
    volumes:
      - "./acme.json:/acme.json"
      - "/var/run/docker.sock:/var/run/docker.sock"
    restart: always

  db:
    image: mariadb:10.2
    container_name: matomo_db
    volumes:
      - "db:/var/lib/mysql"
    environment:
      - "MYSQL_ALLOW_EMPTY_PASSWORD=yes"
      - "MYSQL_DATABASE=matomo"
      - "MYSQL_USER=matomo"
      - "MYSQL_PASSWORD=asupersecretpassword"
    restart: always

  redis:
    image: redis:4.0-alpine
    container_name: matomo_redis
    restart: always

  matomo:
    image: crazymax/matomo:latest
    container_name: matomo
    depends_on:
      - db
      - redis
    volumes:
      - "matomo:/data"
    labels:
      - "traefik.enable=true"
      - "traefik.backend=matomo"
      - "traefik.port=8000"
      - "traefik.frontend.rule=Host:mckinsey-matomo.brandcast.io"
    env_file:
      - "./matomo.env"
    restart: always

  cron:
    image: crazymax/matomo:latest
    container_name: matomo_cron
    depends_on:
      - matomo
    volumes:
      - "matomo:/data"
    env_file:
      - "./matomo.env"
    environment:
      - "SIDECAR_CRON=1"
      - "CRON_GEOIP=0 2 * * *"
      - "CRON_ARCHIVE=0 * * * *"
      - "ARCHIVE_OPTIONS=--concurrent-requests-per-website=3"
    restart: always

volumes:
  db:
  matomo:
```

Here is the matomo.env
```
TZ=Europe/Paris

MEMORY_LIMIT=256M
UPLOAD_MAX_SIZE=64M
OPCACHE_MEM_SIZE=128
REAL_IP_FROM=0.0.0.0/32
REAL_IP_HEADER=X-Forwarded-For

LOG_LEVEL=WARN

SSMTP_HOST=smtp.brandcast.io
SSMTP_PORT=587
SSMTP_HOSTNAME=mckinsey-matomo.brandcast.io
SSMTP_USER=taylor@brandcast.io
SSMTP_PASSWORD=BigBadPassword!
SSMTP_TLS=YES
```

Connectivity to the server for sure works because like I said I can run the docker-compose provided by Matomo.
