### ISSUE TITLE
Prefilling configuration doesn't seem to work

### ISSUE THREAD

**Issue by alexanderadam** [crazy-max/docker-matomo#36]
Thank you for your work! :pray:
Your image is great (apart from this bug).

I [initially thought this would be a matomo issue](https://github.com/matomo-org/matomo/issues/15803) but it seems to be specific to this image.

#### Steps to reproduce this issue

It should work like specified in [the original feature](https://issues.matomo.org/13676).

1. Set some of the official env variables (i.e. `MATOMO_DATABASE_HOST`, `MATOMO_DATABASE_USERNAME`, `MATOMO_DATABASE_DBNAME`, `MATOMO_DATABASE_PASSWORD`, …)
2. Go to database step of the installation wizard

#### Expected behaviour

> Tell me what should happen

Data should be prefilled correctly.

#### Actual behaviour

> Tell me what happens instead

Env variables are ignored and defaults are prefilled.

### Configuration

```yaml
# docker-compose.yml
version: '3'

services:
  db:
    image: mariadb
    command: --max-allowed-packet=64MB
    restart: always
    env_file:
      - ./db.env

  web:
    image: crazymax/matomo:latest
    restart: always
    ports:
      - 8080:8000
    env_file:
      - ./db.env

```

```env
# db.env
MYSQL_PASSWORD=somepassword
MYSQL_ROOT_PASSWORD=somepassword
MYSQL_DATABASE=somedb
MYSQL_USER=someuser
MATOMO_DATABASE_ADAPTER=mysql
MATOMO_DATABASE_TABLES_PREFIX=test_
MATOMO_DATABASE_USERNAME=someuser
MATOMO_DATABASE_PASSWORD=somepassword
MATOMO_DATABASE_DBNAME=somedb
MATOMO_DATABASE_HOST=db
```
